# Generated by Django 5.0.6 on 2025-08-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Genders',
            },
        ),
        migrations.CreateModel(
            name='Subcaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('caste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcastes', to='profiles.caste')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('caste', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='Tamil', max_length=80)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('income', models.CharField(blank=True, max_length=120)),
                ('height_cm', models.CharField(blank=True, max_length=20)),
                ('weight_kg', models.CharField(blank=True, max_length=20)),
                ('marital_status', models.CharField(blank=True, default='Never Married', max_length=80)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, default='India', max_length=120)),
                ('about', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('approved', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.caste')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.gender')),
                ('subcaste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.subcaste')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
