# Generated by Django 5.0.6 on 2025-08-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amsam_cells',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='rasi_cells',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
