# Generated by Django 5.0.6 on 2025-08-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_amsam_cells_profile_rasi_cells'),
    ]

    operations = [
    ]


def insert_castes_and_subcastes(apps, schema_editor):
    Caste = apps.get_model('profiles', 'Caste')
    Subcaste = apps.get_model('profiles', 'Subcaste')

    # Castes list
    castes = [
        "Mudaliyar", "Vanniya Kula Kshatriyar", "Maruthuvar", "CHETTIYAR", "Nadar",
        "KULALAR / UDAYAR", "KARUNEEGAR", "Jangam / THAMBIRAAR", "Vishvakarma",
        "PILLAI", "Devar", "Bhramin / Iyer", "Adhi Dravidar ( SC )", "Vannar", 
        "Yadava", "Arunthathiyar", "Bhramin / Iyengar", "JAIN", "Cast No Bar /  Intercaste", 
        "VEERAKKUDI VELLAALAR", "Devendra Kula Vellalar", "Paruvatha Raja Kulam (Meenavar)",
        "Kongu Vellala Gounder", "Vettaikaara Nayakkar", "Parkava Kulam (Udaiyar)",
        "Valluvar  ( SC)"
    ]
    
    # Insert castes
    for caste in castes:
        Caste.objects.get_or_create(name=caste)

    # Subcaste data for Mudaliyar
    mudaliyar_caste = Caste.objects.get(name="Mudaliyar")
    mudaliyar_subcastes = [
        "SENGUNTHAR / KAIKOLAR", "AGAMUDAYAR / ARCOT / THULUVA", "Thondai Mandala Saiva Vellaalar",
        "Sub Cast Any", "Nathaman", "Nainar", "Saiva Vellalar / Pillai"
    ]
    
    for subcaste in mudaliyar_subcastes:
        Subcaste.objects.get_or_create(name=subcaste, caste=mudaliyar_caste)

    # Subcaste data for Vanniya Kula Kshatriyar
    vanniya_caste = Caste.objects.get(name="Vanniya Kula Kshatriyar")
    vanniya_subcastes = [
        "Sub cast No bar", "ANY", "Gounder", "Naicker", "Vanniyar /Goundar/ Naikar / Padaiyatchi"
    ]
    
    for subcaste in vanniya_subcastes:
        Subcaste.objects.get_or_create(name=subcaste, caste=vanniya_caste)

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),  # Make sure to reference your initial migration
    ]

    operations = [
        migrations.RunPython(insert_castes_and_subcastes),
    ]