# Generated by Django 5.0.6 on 2025-08-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_amsam_cells_profile_rasi_cells'),
        ('profiles', '0003_auto_20250815_0007'),
    ]

    operations = [
    ]
