# Generated by Django 5.0.6 on 2025-08-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_merge_20250815_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
