# Generated by Django 5.0.6 on 2025-08-14 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_alternate_contact_profile_complexion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiblingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('elder_brother', 'Elder Brother'), ('younger_brother', 'Younger Brother'), ('elder_sister', 'Elder Sister'), ('younger_sister', 'Younger Sister')], max_length=20)),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], max_length=10)),
                ('count', models.PositiveIntegerField(default=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siblings', to='profiles.profile')),
            ],
        ),
    ]
