# Generated by Django 5.0.6 on 2025-08-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_siblinginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo/')),
                ('email', models.EmailField(max_length=254)),
                ('phone1', models.CharField(max_length=20, verbose_name='Primary Phone')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary Phone')),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Company Details',
            },
        ),
    ]
