# Generated by Django 5.0.6 on 2025-08-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='long_desc',
            field=models.TextField(null=True),
        ),
    ]
