# Generated by Django 5.0.6 on 2025-08-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_about_long_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='father_occupation',
            new_name='father_name_and_occupation',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='mother_occupation',
            new_name='mother_name_and_occupation',
        ),
    ]
