# Generated by Django 5.0.6 on 2025-08-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_remove_profile_amsam_cells_remove_profile_rasi_cells_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rasi_8',
            new_name='amsam_empty1',
        ),
        migrations.AddField(
            model_name='profile',
            name='amsam_empty2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='amsam_empty3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='amsam_empty4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='rasi_empty1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='rasi_empty2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='rasi_empty3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='rasi_empty4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
