# Generated by Django 5.0.6 on 2025-08-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_rename_rasi_8_profile_amsam_empty1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rasi_8',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
