# Generated by Django 5.0.6 on 2025-08-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_profile_rasi_8'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(help_text='Eg: Home, About, Contact', max_length=150, unique=True)),
                ('title', models.CharField(help_text='Meta Title for SEO', max_length=255)),
                ('description', models.TextField(help_text='Meta Description for SEO')),
                ('keywords', models.TextField(help_text='Comma separated keywords')),
                ('iframe_map', models.TextField(blank=True, help_text='Google Map iframe embed code', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Setting',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
    ]
