# Generated by Django 5.0.6 on 2025-08-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='title',
            field=models.TextField(help_text='Meta Title for SEO', max_length=255),
        ),
    ]
